### ISSUE TITLE
structRefFromNonStruct Error when simulating (and material assignement check error)

### ISSUE THREAD

**Issue by FantaVisionFV** [Frudawski/LUMOS#2]
I have an issue during the simulation of a simple test. It gives me this error: 
"Warning: 'One or more surface does not have a material assigned!'" even if I've attached materials to all meshes.
I was able to skip the check by commenting the lines in spec_simulation.m, but the real problem is that rendering doesn't work:

MATLAB:structRefFromNonStruct
Dot indexing is not supported for variables of this type.
Error at line: 94 in surfaces_radiosity_calculation.m:
Error at line: 5973 in uitoggletool17_ClickedCallback.m:
Error at line: 95 in gui_mainfcn.m:
Error at line: 42 in spec_simulation.m:
Error at line: 0 in @(hObject,eventdata)spec_simulation('uitoggletool17_ClickedCallback',hObject,eventdata,guidata(hObject)).m

I'm using the latest version of LUMOS and Lighting Toolbox with Matlab R2022b (tested also on 2023a and 2021a) without other addons

**Comment by Frudawski** [comment]
I was not able to recreate this issue. Please make sure, that also the environment_ground material is applied. If that does not work, you can attach your example file and I will have a look.

Concerning the rendering problem, there was another problem I have fixed with the latest version 1.06. 

Sorry for your troubles, it seems that I've been too thorough in cleaning up old features and pieces of code that should no longer be necessary.

**Comment by FantaVisionFV** [comment]
Thank you for your help, but sadly it still doesn't work. It gives me the same issues like yesterday.
I've uploaded a very simple scene so you could have a look. Maybe I'm missing something?
[project_02-Jun-2023.zip](https://github.com/Frudawski/LUMOS/files/11633604/project_02-Jun-2023.zip)

**Comment by antoniorusso200** [comment]
I have the same issue. Rendering doesn't work. I have the same problem of FantaVisionFV and I displayed the same error in the command window:
`
MATLAB:structRefFromNonStruct
Dot indexing is not supported for variables of this type.
Error at line: 94 in surfaces_radiosity_calculation.m:
Error at line: 5973 in uitoggletool17_ClickedCallback.m:
Error at line: 95 in gui_mainfcn.m:
Error at line: 42 in spec_simulation.m:
Error at line: 0 in @(hObject,eventdata)spec_simulation('uitoggletool17_ClickedCallback',hObject,eventdata,guidata(hObject)).m
`

[example.spr.zip](https://github.com/Frudawski/LUMOS/files/11633883/example.spr.zip)

**Comment by Frudawski** [comment]
In both cases, the problem lies in incomplete luminaire data. The following steps are neccessary:
1) Import one or more EULUMDAT files, e.g. the lambert.ldt file from the Lighting Toolbox or any ldt file from a munafacturer.
2) Imort spectral data, for test purposes you can use the LUMOS material data or create standard illuminant data with the ciespec function in the Lighting Toolbox.
3) Applythe EULUMDAT and spectral data to any luminaire by selecting it in the list on the left side and than mark any of the checkboxes in the table.

Alternatively, you could use spectral daylight data for testing. The specsky function from the Lighting Toolbox can create spectral sky data.

One extra note, LUMOS is not good in coplanar data evaluation, hence I would suggest to move the luminaires a few mm or cm from the wall.

I found some further bugs in the luminaire loading and displaying functions and fixed those in the new version 1.07.

**Comment by FantaVisionFV** [comment]
Thank you again, I followed the steps and now it's rendering.
In the last commit there was still a problem in importing EULUMDAT data:

Unrecognized function or variable 'read_ldt'.
Error in spec_simulation>load_LDT (line 11235)
        ldt{nr} = read_ldt(filename);

but it was easy to fix because you've named the function "readldt".

I just can't figure it out how to make the rendering properly because the room rendering is black (illuminance is 0) and I can't see the observer perspective (spectral fisheye image). 
In the command window there is the following error in the end:

MATLAB:structRefFromNonStruct
Dot indexing is not supported for variables of this type.
Error at line: 67 in lum2IE.m:
Error at line: 153 in hyperspecfisheye.m:
Error at line: 1375 in surfaces_radiosity_calculation.m:
Error at line: 5973 in uitoggletool17_ClickedCallback.m:
Error at line: 95 in gui_mainfcn.m:
Error at line: 42 in spec_simulation.m:
Error at line: 0 in @(hObject,eventdata)spec_simulation('uitoggletool17_ClickedCallback',hObject,eventdata,guidata(hObject)).m:

I don't know if it is my fault since i'm new in this field, but I would appreciate if you provide some working examples.

**Comment by Frudawski** [comment]
It is not your fault, LUMOS is currently not documented, I am well aware of that.

I attached a simple example project.
[LUMOS_example.zip](https://github.com/Frudawski/LUMOS/files/11636390/LUMOS_example.zip)
